
//**************************************************************************
//**
//** zcommon.acs
//**
//**************************************************************************

// If you are not using the -h command line switch and do not want to use
// WadAuthor's error checker, you can uncomment the following line to shave
// a few bytes off the size of compiled scripts.
//#nowadauthor

#include "zspecial.acs"
#include "zdefs.acs"
#include "zwvars.acs"
