------------------------------------------------------------------------

HEXEN.NAMES =
{
  -- these tables provide *additional* words to those in naming.lua

  GOTHIC =
  {
    lexicon =
    {
      a =
      {
        Wooded=30,
        Silent=20,
        Mysterious=10,
        Deathly=10,
        Dark=20,
        Bright=10,
        Luminous=10,
        Twilight=10,
        Ruined=10,
        Abandoned=20,
        Guarded=15,
        Lost=15,
        Secret=10,
        Barbarain=5,
        Monstrous=15,
        Dead=10,
        Faerie=10,
        Enchanted=5,
        Inhuman=5,
      },

      n =
      {
        Wood=30,
        Woods=20,
        Forest=10,
        Woodland=10,
        Seminary=20,
        Monestary=10,
        Mountain=10,
        Catacombs=20,
        Keep=15,
        Castle=20,
        Fortress=15,
        Fort=10,
        Barbican=5,
        Tower=10,
        Outpost=15,
        Manor=15,
        dungeon=15,
        Necropolis=10,
        Cavern=20,
        Cave=10,
        Tomb=25,
        Crypt=15,
        Barrow=15,
        Mound=5,
        ["Burial Mound"]=5,
        Mere=10,
        Mire=15,
        Bog=10,
        Swamp=10,
        Marsh=15,
        Desert=5,
        Waste=15,
        Wasteland=15,
        Badlands=10,
        Village=20,
        Hamlet=15,
        City=15,
        Settlement=10,
        Township=10,
        Colony=5,
        Town=5,
        Encampment=5,
        Citadel=10,
        Plaza=5,
        Square=5,
        Kingdom=15,
        Stronghold=5,
        Palace=20,
        Courtyard=10,
        Court=10,
        Halls=10,
        Hollow=20,
        Valley=15,
        Plateau=10,
        Mesa=5,
        Sewer=5,
        Effluvium=5,
        Plane=10,
        Dimension=15,
        Realm=10,
        Portal=10,
        Portals=5,
      },

      m =
      {
        -- Duplicated in 'h' since it doesn't seem to do anything yet
        -- Comon Hexen monster
        Ettins=20,
        Afriti=20,
        Wendigos=5,
        ["Chaos Serpents"]=20,
        Centaurs=20,
        Slaughtars=10,
        ["Dark Bishops"]=20,
        Reivers=10,
        -- Other creatures that work
        Demons=10,
        Dragons=5,
        Fairies=15,
        Elves=5,
        Trolls=10,
        Nymphs=5,
        Satyrs=5,
        Ghosts=15,
        Shadows=30,
        Spirits=25,
        ["Evil Spirits"]=10,
        Beasts=20,
        Animals=5,
        Serpents=10,
        Humans=2,
        ["the People"]=3,
        ["the Legion"]=8,
        Legionaires=6,
        Legions=6,
        Magi=20,
        Priests=6,
        ["the Priesthood"]=10,
        Clergy=4,
        Barbarians=10,
        ["the Wildmen"]=10,
        ["the Untaimed"]=10,
        Corpses=10,
      },

      h =
      {
        Sorcery=25,
        Magic=10,
        Mystery=10,
        Mysteries=15,
        Theurgy=10,
        Thaumaturgy=10,
        Diablerie=10,
        Necromancy=10,
        Conjuring=5,
        Illusion=10,
        Alchemy=5,
        Dreams=5,
        Dreaming=5,
        Nightmares=10,
        Darkness=10,
        Enchantment=10,
        -- Comon Hexen monster
        ["the Ettins"]=20,
        ["the Afriti"]=20,
        ["the Wendigo"]=5,
        ["Chaos Serpents"]=20,
        ["the Centaurs"]=20,
        ["the Slaughtars"]=10,
        ["Dark Bishops"]=20,
        ["the Reiver"]=5,
        Wraiths=10,
        ["the Stalkers"]=5,
        -- Other creatures that work
        Demons=15,
        Dragons=5,
        Fairies=15,
        ["the Elves"]=5,
        Trolls=10,
        ["the Nymphs"]=5,
        ["the Satyrs"]=5,
        Ghosts=15,
        Shadows=30,
        Spirits=25,
        ["Evil Spirits"]=10,
        Beasts=20,
        ["the Animals"]=5,
        Serpents=10,
        ["the Humans"]=2,
        ["the People"]=3,
        ["the Legion"]=8,
        Legionaires=6,
        Legions=6,
        ["the Magi"]=20,
        Priests=6,
        ["the Priesthood"]=10,
        ["the Clergy"]=4,
        Barbarians=10,
        ["the Wildmen"]=10,
        ["the Untaimed"]=10,
        Corpses=10,
      },

      e =
      {
        Korax=100,
        ["D'Sparil"]=25,
        Eidolon=10,
        ["the Heresiarch"]=75,
        Zedek=30,
        Menalkir=30,
        Traductus=30,
        Circe=5,
        Hades=5,
        Persephone=5,
        Hecate=5,
        Medea=1,
        Loki=5,
        Hel=3,
        ["Frau Hoelle"]=2,
        ["Black Annis"]=5,
        Cerridwen=4,
        Morgaina=5,
        Anubis=3,
        Set=2,
      },
    },
  },
},

