
---------------------------------------------
--  LineDef Translation for Hexen / ZDoom
---------------------------------------------

XLAT_SPEC =
{
  Polyobj_StartLine = { id=1 }
  Polyobj_RotateLeft = { id=2 }
  Polyobj_RotateRight = { id=3 }
  Polyobj_Move = { id=4 }
  Polyobj_ExplicitLine = { id=5 }
  Polyobj_MoveTimes8 = { id=6 }
  Polyobj_DoorSwing = { id=7 }
  Polyobj_DoorSlide = { id=8 }
  Line_Horizon = { id=9 }
  Door_Close = { id=10 }
  Door_Open = { id=11 }
  Door_Raise = { id=12 }
  Door_LockedRaise = { id=13 }
  Door_Animated = { id=14 }
  Autosave = { id=15 }
  Transfer_WallLight = { id=16 }
  Thing_Raise = { id=17 }
  StartConversation = { id=18 }
  Thing_Stop = { id=19 }
  Floor_LowerByValue = { id=20 }
  Floor_LowerToLowest = { id=21 }
  Floor_LowerToNearest = { id=22 }
  Floor_RaiseByValue = { id=23 }
  Floor_RaiseToHighest = { id=24 }
  Floor_RaiseToNearest = { id=25 }
  Stairs_BuildDown = { id=26 }
  Stairs_BuildUp = { id=27 }
  Floor_RaiseAndCrush = { id=28 }
  Pillar_Build = { id=29 }
  Pillar_Open = { id=30 }
  Stairs_BuildDownSync = { id=31 }
  Stairs_BuildUpSync = { id=32 }
  ForceField = { id=33 }
  ClearForceField = { id=34 }
  Floor_RaiseByValueTimes8 = { id=35 }
  Floor_LowerByValueTimes8 = { id=36 }
  Floor_MoveToValue = { id=37 }
  Ceiling_Waggle = { id=38 }
  Teleport_ZombieChanger = { id=39 }
  Ceiling_LowerByValue = { id=40 }
  Ceiling_RaiseByValue = { id=41 }
  Ceiling_CrushAndRaise = { id=42 }
  Ceiling_LowerAndCrush = { id=43 }
  Ceiling_CrushStop = { id=44 }
  Ceiling_CrushRaiseAndStay = { id=45 }
  Floor_CrushStop = { id=46 }
  Ceiling_MoveToValue = { id=47 }
  Sector_Attach3dMidtex = { id=48 }
  GlassBreak = { id=49 }
  ExtraFloor_LightOnly = { id=50 }
  Sector_SetLink = { id=51 }
  Scroll_Wall = { id=52 }
  Line_SetTextureOffset = { id=53 }
  Sector_ChangeFlags = { id=54 }
  Line_SetBlocking = { id=55 }
  Line_SetTextureScale = { id=56 }
  Sector_SetPortal = { id=57 }
  Sector_CopyScroller = { id=58 }
  Polyobj_OR_MoveToSpot = { id=59 }
  Plat_PerpetualRaise = { id=60 }
  Plat_Stop = { id=61 }
  Plat_DownWaitUpStay = { id=62 }
  Plat_DownByValue = { id=63 }
  Plat_UpWaitDownStay = { id=64 }
  Plat_UpByValue = { id=65 }
  Floor_LowerInstant = { id=66 }
  Floor_RaiseInstant = { id=67 }
  Floor_MoveToValueTimes8 = { id=68 }
  Ceiling_MoveToValueTimes8 = { id=69 }
  Teleport = { id=70 }
  Teleport_NoFog = { id=71 }
  ThrustThing = { id=72 }
  DamageThing = { id=73 }
  Teleport_NewMap = { id=74 }
  Teleport_EndGame = { id=75 }
  TeleportOther = { id=76 }
  TeleportGroup = { id=77 }
  TeleportInSector = { id=78 }
  Thing_SetConversation = { id=79 }
  ACS_Execute = { id=80 }
  ACS_Suspend = { id=81 }
  ACS_Terminate = { id=82 }
  ACS_LockedExecute = { id=83 }
  ACS_ExecuteWithResult = { id=84 }
  ACS_LockedExecuteDoor = { id=85 }
  Polyobj_MoveToSpot = { id=86 }
  Polyobj_Stop = { id=87 }
  Polyobj_MoveTo = { id=88 }
  Polyobj_OR_MoveTo = { id=89 }
  Polyobj_OR_RotateLeft = { id=90 }
  Polyobj_OR_RotateRight = { id=91 }
  Polyobj_OR_Move = { id=92 }
  Polyobj_OR_MoveTimes8 = { id=93 }
  Pillar_BuildAndCrush = { id=94 }
  FloorAndCeiling_LowerByValue = { id=95 }
  FloorAndCeiling_RaiseByValue = { id=96 }
  Ceiling_LowerAndCrushDist = { id=97 }
  Sector_SetTranslucent = { id=98 }
  Floor_RaiseAndCrushDoom = { id=99 }
  Scroll_Texture_Left = { id=100 }
  Scroll_Texture_Right = { id=101 }
  Scroll_Texture_Up = { id=102 }
  Scroll_Texture_Down = { id=103 }
  Light_ForceLightning = { id=109 }
  Light_RaiseByValue = { id=110 }
  Light_LowerByValue = { id=111 }
  Light_ChangeToValue = { id=112 }
  Light_Fade = { id=113 }
  Light_Glow = { id=114 }
  Light_Flicker = { id=115 }
  Light_Strobe = { id=116 }
  Light_Stop = { id=117 }
  Plane_Copy = { id=118 }
  Thing_Damage = { id=119 }
  Radius_Quake = { id=120 }
  Line_SetIdentification = { id=121 }
  Thing_Move = { id=125 }
  Thing_SetSpecial = { id=127 }
  ThrustThingZ = { id=128 }
  UsePuzzleItem = { id=129 }
  Thing_Activate = { id=130 }
  Thing_Deactivate = { id=131 }
  Thing_Remove = { id=132 }
  Thing_Destroy = { id=133 }
  Thing_Projectile = { id=134 }
  Thing_Spawn = { id=135 }
  Thing_ProjectileGravity = { id=136 }
  Thing_SpawnNoFog = { id=137 }
  Floor_Waggle = { id=138 }
  Thing_SpawnFacing = { id=139 }
  Sector_ChangeSound = { id=140 }
  Teleport_NoStop = { id=154 }
  SetGlobalFogParameter = { id=157 }
  FS_Execute = { id=158 }
  Sector_SetPlaneReflection = { id=159 }
  Sector_Set3DFloor = { id=160 }
  Sector_SetContents = { id=161 }
  Ceiling_CrushAndRaiseDist = { id=168 }
  Generic_Crusher2 = { id=169 }
  Sector_SetCeilingScale2 = { id=170 }
  Sector_SetFloorScale2 = { id=171 }
  Plat_UpNearestWaitDownStay = { id=172 }
  NoiseAlert = { id=173 }
  SendToCommunicator = { id=174 }
  Thing_ProjectileIntercept = { id=175 }
  Thing_ChangeTID = { id=176 }
  Thing_Hate = { id=177 }
  Thing_ProjectileAimed = { id=178 }
  ChangeSkill = { id=179 }
  Thing_SetTranslation = { id=180 }
  Plane_Align = { id=181 }
  Line_Mirror = { id=182 }
  Line_AlignCeiling = { id=183 }
  Line_AlignFloor = { id=184 }
  Sector_SetRotation = { id=185 }
  Sector_SetCeilingPanning = { id=186 }
  Sector_SetFloorPanning = { id=187 }
  Sector_SetCeilingScale = { id=188 }
  Sector_SetFloorScale = { id=189 }
  Static_Init = { id=190 }
  SetPlayerProperty = { id=191 }
  Ceiling_LowerToHighestFloor = { id=192 }
  Ceiling_LowerInstant = { id=193 }
  Ceiling_RaiseInstant = { id=194 }
  Ceiling_CrushRaiseAndStayA = { id=195 }
  Ceiling_CrushAndRaiseA = { id=196 }
  Ceiling_CrushAndRaiseSilentA = { id=197 }
  Ceiling_RaiseByValueTimes8 = { id=198 }
  Ceiling_LowerByValueTimes8 = { id=199 }
  Generic_Floor = { id=200 }
  Generic_Ceiling = { id=201 }
  Generic_Door = { id=202 }
  Generic_Lift = { id=203 }
  Generic_Stairs = { id=204 }
  Generic_Crusher = { id=205 }
  Plat_DownWaitUpStayLip = { id=206 }
  Plat_PerpetualRaiseLip = { id=207 }
  TranslucentLine = { id=208 }
  Transfer_Heights = { id=209 }
  Transfer_FloorLight = { id=210 }
  Transfer_CeilingLight = { id=211 }
  Sector_SetColor = { id=212 }
  Sector_SetFade = { id=213 }
  Sector_SetDamage = { id=214 }
  Teleport_Line = { id=215 }
  Sector_SetGravity = { id=216 }
  Stairs_BuildUpDoom = { id=217 }
  Sector_SetWind = { id=218 }
  Sector_SetFriction = { id=219 }
  Sector_SetCurrent = { id=220 }
  Scroll_Texture_Both = { id=221 }
  Scroll_Texture_Model = { id=222 }
  Scroll_Floor = { id=223 }
  Scroll_Ceiling = { id=224 }
  Scroll_Texture_Offsets = { id=225 }
  ACS_ExecuteAlways = { id=226 }
  PointPush_SetForce = { id=227 }
  Plat_RaiseAndStayTx0 = { id=228 }
  Thing_SetGoal = { id=229 }
  Plat_UpByValueStayTx = { id=230 }
  Plat_ToggleCeiling = { id=231 }
  Light_StrobeDoom = { id=232 }
  Light_MinNeighbor = { id=233 }
  Light_MaxNeighbor = { id=234 }
  Floor_TransferTrigger = { id=235 }
  Floor_TransferNumeric = { id=236 }
  ChangeCamera = { id=237 }
  Floor_RaiseToLowestCeiling = { id=238 }
  Floor_RaiseByValueTxTy = { id=239 }
  Floor_RaiseByTexture = { id=240 }
  Floor_LowerToLowestTxTy = { id=241 }
  Floor_LowerToHighest = { id=242 }
  Exit_Normal = { id=243 }
  Exit_Secret = { id=244 }
  Elevator_RaiseToNearest = { id=245 }
  Elevator_MoveToFloor = { id=246 }
  Elevator_LowerToNearest = { id=247 }
  HealThing = { id=248 }
  Door_CloseWaitOpen = { id=249 }
  Floor_Donut = { id=250 }
  FloorAndCeiling_LowerRaise = { id=251 }
  Ceiling_RaiseToNearest = { id=252 }
  Ceiling_LowerToLowest = { id=253 }
  Ceiling_LowerToFloor = { id=254 }
  Ceiling_CrushRaiseAndStaySilA = { id=255 }
}

XLAT =
{
}

