#----------------------------------------------------------------
# Testing Makefile
#----------------------------------------------------------------

all:
	rm -f ../TEST.wad
	$(MAKE) ../TEST.wad

../TEST.wad:
	lua run_test.lua $(SEED)
	wadlc TEMP.txt TEMP.wad
	glbsp -pack -warn TEMP.wad -o ../TEST.wad

clean:
	rm -f ../TEST.wad ../TEST.bak TEMP.wad
	rm -f TEMP.txt LOGS.txt CONFIG.cfg

.PHONY: all clean

#--- editor settings ------------
# vi:ts=8:sw=8:noexpandtab
