<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
  <meta name="robots" content="all">

  <title> OBLIGE <use O_WHERE> </title>

  <link rel="shortcut icon" href="http://oblige.sourceforge.net/favicon.ico" type="image/vnd.microsoft.icon">

  <script type="text/javascript"></script>

  <style type="text/css" title="currentStyle">
    @import "new.css";
  </style>
</head>

<body>

<h1> OBLIGE Level Maker </h1>
<h2>Random map generator for classic FPS games</h2>

