
<block TopCorners>
  <img src="top_L.png" class="floatL" alt="" width="24" height="24">
  <img src="top_R.png" class="floatR" alt="" width="24" height="24">
</block>


<block MenuWhere>
  <span> <use where> </span>
</block>

<block MenuHome>
  <a href="http://oblige.sourceforge.net/">Home</a>
</block>

<block MenuDocs>
  <a href="doc_usage.html">Documentation</a>
</block>

<block MenuModding>
  <a href="mod_monsters.html">Modding</a>
</block>


<block SubSpacer>
  &nbsp; &nbsp; &nbsp;
</block>

<block SubWhere>
  <span> &gt;<use where>&lt; </span>
</block>


<block IndexMENU>
  <div class="menu">
  <use TopCorners>
  <use MenuWhere where="HOME">
  <use MenuDocs>
  <use MenuModding>
  </div>
</block>

<block IndexNews>
  <a href="index.html">News</a>
</block>

<block IndexScreens>
  <a href="i_screens.html">Screenshots</a>
</block>

<block IndexDownload>
  <a href="i_download.html">Download</a>
</block>

<block IndexForums>
  <a href="http://oblige.sourceforge.net/forum/">Forum</a>
</block>


<block DocMENU>
  <div class="menu">
  <use TopCorners>
  <use MenuHome>
  <use MenuWhere where="DOCUMENTATION">
  <use MenuModding>
  </div>
</block>

<block DocUsage>
  <a href="doc_usage.html">Usage</a>
</block>

<block DocAbout>
  <a href="doc_about.html">About</a>
</block>

<block DocCredits>
  <a href="doc_credits.html">Credits</a>
</block>

<block DocGlossary>
  <a href="doc_glossary.html">Glossary</a>
</block>

<block DocFAQ>
  <a href="doc_faq.html">FAQ</a>
</block>

<block DocHistory>
  <a href="doc_history.html">History</a>
</block>


<block BlogMENU>
  <div class="menu">
  <use TopCorners>
  <use MenuHome>
  <use MenuWhere where="BLOGS">
  </div>
</block>

<block BlogMar2008>
  <a href="blog_mar2008.html">Mar-2008</a>
</block>

<block BlogNov2008>
  <a href="blog_nov2008.html">Nov-2008</a>
</block>


<block ModMENU>
  <div class="menu">
  <use TopCorners>
  <use MenuHome>
  <use MenuDocs>
  <use MenuWhere where="MODDING">
  </div>
</block>

