
<block TopCorners>
  <img src="top_L.png" class="floatL" alt="" width="24" height="24">
  <img src="top_R.png" class="floatR" alt="" width="24" height="24">
</block>


<block MenuHome>
  <a href="http://oblige.sourceforge.net/">Home</a>
</block>

<block MenuDocs>
  <a href="doc_usage.html">Documentation</a>
</block>

<block MenuWhere>
  <span> <use where> </span>
</block>


<block SubSpacer>
  &nbsp; &nbsp; &nbsp;
</block>

<block SubWhere>
  <span> &gt;<use where>&lt; </span>
</block>


<block IndexNews>
  <a href="index.html">News</a>
</block>

<block IndexScreens>
  <a href="i_screens.html">Screenshots</a>
</block>

<block IndexDownload>
  <a href="i_download.html">Download</a>
</block>


<block DocUsage>
  <a href="doc_usage.html">Usage</a>
</block>

<block DocAbout>
  <a href="doc_about.html">About</a>
</block>

<block DocCredits>
  <a href="doc_credits.html">Credits</a>
</block>

<block DocHistory>
  <a href="doc_history.html">History</a>
</block>

