<div class="bottomcurve">
<img src="bottom_L.png" class="floatL" alt="" width="24" height="24">
<img src="bottom_R.png" class="floatR" alt="" width="24" height="24">
</div>

<br>

<div class="floatR">
      <a HREF="http://sourceforge.net/projects/oblige">
        <img src="http://sourceforge.net/sflogo.php?group_id=176314&amp;type=3" 
         width="125" height="37" alt="SourceForge.net" 
         align="MIDDLE" border="0" hspace="1">
      </a>
</div>

<span style="font-size: smaller"> &copy; 2014  Andrew Apted </span>

</body>
</html>
